### ISSUE TITLE
look back history on new request doesnt look back long enough so we get duplicates

### ISSUE THREAD

**Issue by hedata** [hedata/reboting_fulfillment#3]
at the moment each stream is set to 100 history items to look at when ignoring extracted items

at the moment the client gets a new item every 3.4 secs
and for each requests items extracted in the last 2 hours = 7200 sec
so the history should look back max of 2117 items (not feasable)

google news gets new data every approx 7 minutes
gdelt claims data updates every 35 minutes so probably 50 minute window is fine
if we have 50 minutes = 3000 secs we need a history of approx 900 items

**Comment by kernoelpanic** [comment]
As I see it the goals are as follows:
* Do not send the same item in an output stream twice -> problem saving all sent files might not be feasible or at least inefficient.
* Rate items from all sources (scrapers) and send out best rated items when requested.

To improve upon the current design in https://github.com/hedata/reboting_fulfillment/blob/79eee7aff922e8b5295b9c5513da0265a086b6bd/src/controller/stream/actions.js#L37-L133
I have the following suggestions:

### Decouple the rating, requesting and extracting of items
The rating, requesting of a new item and extracting of items are three different tasks which can be fulfilled by separate services with different time constraints. 
Now only extracting and requesting are (more or less) separated -- they are handled by different services but still their individual characteristics have to be considered when requesting an item. 
The rating happens ad-hoc when an item is requested. So all comes together when an item is requested, which is not optimal because this happens often and should be handled fast. 

#### Rater service 
I would suggest to have a dedicated rater service which is executed as a separate service and goes over all active output streams and ratings available for them to look for suitable new items amongst the newly scraped input streams. This can happen in the background. For all streams some best ranked items are cached and served immediately if requested. The rater service(s) take(s) care of keeping this buffer filled. 

To reduce the data load and still keep the probability of sending duplicated within one output stream 
bloomfilters might be handy. This might do for now: https://www.npmjs.com/package/bloomfilter

PS: This rater service design would also work well for more complex (machine learning) ratings in the future -- I would even argue that this is a prerequisite for more elaborate ratings. 

#### instream 
To allow for external scrapers and interfaces have a generic input stream interface.
This would allow to get custom input streams and write scrapers in some other language => faster. 
(Implementing this has already been started: https://github.com/hedata/reboting_fulfillment/tree/master/src/controller/instream

#### Requesting items
Here we need a session for each stream, which just returns the best ranked item form the stream cache of ranked items. 
This design would also allow to keep a backlog for stream participants (users) which have not requested certain items.
